version: '3'

services:
  app:
    container_name: app-vite-dockerfile
    image: docker-binding-volumes
    build: .
    ports:
      - 3100:3100    
    volumes:
    #  - type: bind
    #    source: ./
    #    target: /app/
      - ./src:/app/src:bind
      # - ./src:/app/src:bind
    # tty: true    