version: "3.4"
services:
 vite_docker:
    image: node:18-alpine
    container_name: app-vite
    entrypoint: /bin/sh
    ports:
     - 3100:3100
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true